services:
  - type: web
    name: job-portal-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        value: your-db-host
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: Ajayraj@1515
      - key: DB_NAME
        value: job_portal
